import React from 'react';

/**
 * @description 然然的设计准则预览组件
 * 技术栈: Next.js + TypeScript + Tailwind CSS
 * 视觉风格: 严格蓝色系，蓝紫渐变，无红绿黄
 */

const DesignSystem = () => {
  return (
    <div className="min-h-screen bg-slate-50 p-8 font-sans text-slate-900">
      <header className="mb-12 border-b border-blue-100 pb-6">
        <h1 className="text-3xl font-bold text-blue-900">RanRan Design System</h1>
        <p className="text-slate-500">Project: OpenClaw | Theme: Elegant Blue</p>
      </header>

      <section className="space-y-12">
        {/* Color Palette */}
        <div>
          <h2 className="mb-4 text-xl font-semibold text-blue-800">1. Core Palette (蓝色系)</h2>
          <div className="flex gap-4">
            <div className="h-20 w-20 rounded-lg bg-blue-50 shadow-inner flex items-end p-2 text-xs text-blue-900">Blue 50</div>
            <div className="h-20 w-20 rounded-lg bg-blue-200 shadow-inner flex items-end p-2 text-xs text-blue-900">Blue 200</div>
            <div className="h-20 w-20 rounded-lg bg-blue-500 shadow-md flex items-end p-2 text-xs text-white font-bold">Primary</div>
            <div className="h-20 w-20 rounded-lg bg-blue-700 shadow-md flex items-end p-2 text-xs text-white font-bold">Deep</div>
            <div className="h-20 w-20 rounded-lg bg-indigo-900 shadow-md flex items-end p-2 text-xs text-white font-bold">Darkest</div>
          </div>
        </div>

        {/* Gradients */}
        <div>
          <h2 className="mb-4 text-xl font-semibold text-blue-800">2. Accents (蓝紫渐变强调)</h2>
          <div className="flex gap-6">
            <button className="rounded-full bg-gradient-to-r from-blue-600 to-indigo-600 px-8 py-3 font-medium text-white shadow-lg transition-all hover:scale-105 active:scale-95">
              Gradient Action
            </button>
            <div className="flex items-center justify-center rounded-xl bg-gradient-to-br from-blue-500 via-indigo-500 to-purple-600 p-[2px] shadow-lg">
              <div className="rounded-[10px] bg-white px-6 py-2.5">
                <span className="bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-lg font-bold text-transparent">
                  Premium Border
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Rule Validation */}
        <div className="rounded-2xl border border-blue-200 bg-white p-6 shadow-sm">
          <h2 className="mb-4 text-xl font-semibold text-blue-800">3. Rule Check (色彩禁令检查)</h2>
          <ul className="space-y-3">
            <li className="flex items-center text-slate-700">
              <span className="mr-3 flex h-5 w-5 items-center justify-center rounded-full bg-blue-100 text-blue-600 text-[10px]">✓</span>
              严禁大红: <span className="ml-2 font-mono text-xs text-slate-400">#FF0000 -> Rejected</span>
            </li>
            <li className="flex items-center text-slate-700">
              <span className="mr-3 flex h-5 w-5 items-center justify-center rounded-full bg-blue-100 text-blue-600 text-[10px]">✓</span>
              严禁大绿: <span className="ml-2 font-mono text-xs text-slate-400">#00FF00 -> Rejected</span>
            </li>
            <li className="flex items-center text-slate-700">
              <span className="mr-3 flex h-5 w-5 items-center justify-center rounded-full bg-blue-100 text-blue-600 text-[10px]">✓</span>
              严禁黄色: <span className="ml-2 font-mono text-xs text-slate-400">#FFFF00 -> Rejected</span>
            </li>
          </ul>
        </div>
      </section>

      <footer className="mt-20 text-center text-sm text-slate-400">
        Generated by RanRan ✨ | {new Date().toLocaleDateString()}
      </footer>
    </div>
  );
};

export default DesignSystem;
